package UI.GUI;

import UI.ValiKommunikaatio;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JOptionPane;

/**
 * BasicGUI on luokka, jossa suurin osa graafisest akäyttöliittymästä on
 * toteutettu.
 * Luokka hyödyntää kylelyogiikan komponentteja kysellessään sanoja ja
 * vastineita käyttäjältä.
 *
 * @author jarmo
 */
public class BasicGUI extends javax.swing.JFrame {

    private boolean kysSuunta = true;
    ValiKommunikaatio k = new ValiKommunikaatio(true);

    /**
     * Creates new form BasicGUI
     */
    public BasicGUI() {
        initComponents();


    }

    private void tyhjennaOnnistuminen() {
        MitenMeni.setText("");
    }

    private void disableTarkista() {
        TarkVastaus.setEnabled(false);
    }

    private void enableTarkista() {
        TarkVastaus.setEnabled(true);
    }

    private void asetaKysymys(String kysyttavaSana){
        Kysymys.setText("Anna sanan: " + kysyttavaSana + " vastine:");
        Vastaus.setText("");
        enableTarkista();
        tyhjennaOnnistuminen();
    }
    
    private void kysyNext() {
        String kysyttavaSana = k.kysyNext(kysSuunta);
//        Kysymys.setText("Anna sanan: " + kysyttavaSana + " vastine:");
        asetaKysymys(kysyttavaSana);
//        Vastaus.setText("");
//        tyhjennaOnnistuminen();
//        enableTarkista();
        NaytVastaus.setEnabled(false);
    }
    
    public void kysyPrev(){
        String kysyttavaSana = k.kysyEdellinen(kysSuunta);
//        Kysymys.setText("Anna sanan: " + kysyttavaSana + " vastine:");
        asetaKysymys(kysyttavaSana);
//        Vastaus.setText("");
//        tyhjennaOnnistuminen();
//        enableTarkista();
        NaytVastaus.setEnabled(false);
    }

    private void kysyRandom(){
        String kysyttava = k.kysyRandom(kysSuunta);
//        Kysymys.setText("Anna sanan: " + kysyttava + " vastine:");
        asetaKysymys(kysyttava);
//        Vastaus.setText("");
        tyhjennaOnnistuminen();
//        enableTarkista();
//        NaytVastaus.setEnabled(false);
        
    }
    
    private void kysyLooginen(){
        String kysyttava = k.kysyLooginen(kysSuunta);
//        Kysymys.setText("Anna sanan: " + kysyttava + " vastine:");
        asetaKysymys(kysyttava);
//        Vastaus.setText("");
        enableTarkista();
//        tyhjennaOnnistuminen();
//        NaytVastaus.setEnabled(false);
        
    }
    
    private void tarkVastaus(){
        tyhjennaOnnistuminen();
        String vastaus = Vastaus.getText();
        boolean onnistui = k.tarkastaVastaus(vastaus);
        Onnistuneet.setText("Oikein: " + k.getOikein());
        Vaarin.setText("Väärin: " + k.getVaarin());
        Yhteensa.setText("Yhteensä: " + k.getYhteensa());
        disableTarkista();
        NaytVastaus.setEnabled(true);
        if (onnistui) {
            MitenMeni.setText("Oikein");
            MitenMeni.setForeground(Color.GREEN);
        }
        if (!onnistui) {
            MitenMeni.setText("Väärin");
            MitenMeni.setForeground(Color.RED);
        }
    }
    
    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SuunnanValitsin = new javax.swing.ButtonGroup();
        Vastineeseen = new javax.swing.JRadioButton();
        Sanaan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Kysymys = new javax.swing.JTextArea();
        Vastaus = new javax.swing.JTextField();
        KysSeuraava = new javax.swing.JButton();
        KysEdellinen = new javax.swing.JButton();
        Random = new javax.swing.JButton();
        Logiikka = new javax.swing.JButton();
        TarkVastaus = new javax.swing.JButton();
        Onnistuneet = new javax.swing.JLabel();
        Vaarin = new javax.swing.JLabel();
        Yhteensa = new javax.swing.JLabel();
        KerrottuTeksti = new javax.swing.JLabel();
        MitenMeni = new javax.swing.JLabel();
        NaytVastaus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        MenuValikko = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        SuljeTaaIkkuna = new javax.swing.JMenuItem();
        AvaaUusiFilu = new javax.swing.JMenuItem();
        LopetaMenuItem = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        AboutMenuitem2 = new javax.swing.JMenuItem();
        CopyrightInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kyselyohjelma");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 400));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                formKeyTyped(evt);
            }
        });

        SuunnanValitsin.add(Vastineeseen);
        Vastineeseen.setSelected(true);
        Vastineeseen.setText("Sana -> Vastine");
        Vastineeseen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VastineeseenActionPerformed(evt);
            }
        });

        SuunnanValitsin.add(Sanaan);
        Sanaan.setText("Vastine -> Sana");
        Sanaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanaanActionPerformed(evt);
            }
        });

        Kysymys.setColumns(20);
        Kysymys.setEditable(false);
        Kysymys.setLineWrap(true);
        Kysymys.setRows(5);
        Kysymys.setWrapStyleWord(true);
        jScrollPane1.setViewportView(Kysymys);

        Vastaus.setToolTipText("Kirjoita vastaus tähän kenttään");

        KysSeuraava.setText("Kysy Seuraava");
        KysSeuraava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KysSeuraavaActionPerformed(evt);
            }
        });
        KysSeuraava.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                KysSeuraavaKeyTyped(evt);
            }
        });

        KysEdellinen.setText("Kysy Edellinen");
        KysEdellinen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KysEdellinenActionPerformed(evt);
            }
        });

        Random.setText("Kysy Satunnainen");
        Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomActionPerformed(evt);
            }
        });

        Logiikka.setText("Kysy Painotetusti");
        Logiikka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogiikkaActionPerformed(evt);
            }
        });

        TarkVastaus.setText("Tarkista");
        TarkVastaus.setEnabled(false);
        TarkVastaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarkVastausActionPerformed(evt);
            }
        });

        Onnistuneet.setText("Oikein: 0");

        Vaarin.setText("Väärin: 0");

        Yhteensa.setText("Yhteensä: 0");

        KerrottuTeksti.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        KerrottuTeksti.setText("Arvaa sanan vastine");

        MitenMeni.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N

        NaytVastaus.setText("Näytä Vastaus");
        NaytVastaus.setEnabled(false);
        NaytVastaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaytVastausActionPerformed(evt);
            }
        });

        jLabel1.setText("Valitse suunta");

        jLabel2.setText("Valitse seuraavista");

        jLabel3.setText("Syötä vastauksesi");

        jLabel4.setText("Tulokset");

        FileMenu.setText("File");

        SuljeTaaIkkuna.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        SuljeTaaIkkuna.setText("Sulje tämä ikkuna");
        SuljeTaaIkkuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuljeTaaIkkunaActionPerformed(evt);
            }
        });
        FileMenu.add(SuljeTaaIkkuna);

        AvaaUusiFilu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        AvaaUusiFilu.setText("Avaa uusi tiedosto");
        AvaaUusiFilu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AvaaUusiFiluActionPerformed(evt);
            }
        });
        FileMenu.add(AvaaUusiFilu);

        LopetaMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        LopetaMenuItem.setText("Quit");
        LopetaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LopetaMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(LopetaMenuItem);

        MenuValikko.add(FileMenu);

        HelpMenu.setText("Help");

        AboutMenuitem2.setText("About");
        AboutMenuitem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutMenuitem2ActionPerformed(evt);
            }
        });
        HelpMenu.add(AboutMenuitem2);

        CopyrightInfo.setText("COPYRIGHT");
        CopyrightInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyrightInfoActionPerformed(evt);
            }
        });
        HelpMenu.add(CopyrightInfo);

        MenuValikko.add(HelpMenu);

        setJMenuBar(MenuValikko);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KerrottuTeksti)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Sanaan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Vastineeseen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MitenMeni, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(93, 93, 93))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KysSeuraava, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KysEdellinen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Random)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(TarkVastaus))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Onnistuneet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Vaarin, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(NaytVastaus, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Yhteensa, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Logiikka, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(Vastaus))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 582, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 67, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(MitenMeni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(KerrottuTeksti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Vastineeseen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Sanaan)))
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KysSeuraava)
                    .addComponent(KysEdellinen)
                    .addComponent(Random)
                    .addComponent(Logiikka))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Vastaus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TarkVastaus)
                    .addComponent(NaytVastaus))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Onnistuneet))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Vaarin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Yhteensa)
                .addGap(68, 68, 68))
        );

        getAccessibleContext().setAccessibleName("Kehys1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VastineeseenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VastineeseenActionPerformed
        kysSuunta = true;
    }//GEN-LAST:event_VastineeseenActionPerformed

    private void SanaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanaanActionPerformed
        kysSuunta = false;
    }//GEN-LAST:event_SanaanActionPerformed

    private void KysSeuraavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KysSeuraavaActionPerformed
        //Eli tähän se, mitä seuraavan sanan kysymiseen vaaditaan
//       kysyttavaSana
//        String kysyttavaSana = k.kysyNext(kysSuunta);
//        Kysymys.setText("Anna sanan: " + kysyttavaSana + " vastine:");
//        Vastaus.setText("");
//        tyhjennaOnnistuminen();
//        enableTarkista();
//        NaytVastaus.setEnabled(false);'
        kysyNext();
    }//GEN-LAST:event_KysSeuraavaActionPerformed

    private void KysEdellinenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KysEdellinenActionPerformed
        kysyPrev();
    }//GEN-LAST:event_KysEdellinenActionPerformed

    private void RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomActionPerformed
        kysyRandom();
    }//GEN-LAST:event_RandomActionPerformed

    private void LogiikkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogiikkaActionPerformed
        kysyLooginen();

    }//GEN-LAST:event_LogiikkaActionPerformed

    /**
     * Tarkastaa vastauksen
     *
     * @param evt tapahtuma
     */
    private void TarkVastausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarkVastausActionPerformed
        tarkVastaus();
    }//GEN-LAST:event_TarkVastausActionPerformed

    /**
     * Lopettaa ohjelman suorittamisen
     *
     * @param evt tapahtuma
     */
    private void LopetaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LopetaMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_LopetaMenuItemActionPerformed

    /**
     * Näytä about version ikkuna
     *
     * @param evt tapahtuma
     */
    private void AboutMenuitem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutMenuitem2ActionPerformed
        new AboutVersion().setVisible(true);
    }//GEN-LAST:event_AboutMenuitem2ActionPerformed

    /**
     * Avaa copyright näkymä
     *
     * @param evt tapahtuma
     */
    private void CopyrightInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyrightInfoActionPerformed
        // TODO add your handling code here:

        new Copyright().setVisible(true);
    }//GEN-LAST:event_CopyrightInfoActionPerformed

    /**
     * Näyttää vastauksen
     *
     * @param evt tapahtuma
     */
    private void NaytVastausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaytVastausActionPerformed
        JOptionPane.showMessageDialog(null, "Sanan: \"" + k.getKysytty() + "\" vastine on : \"" + k.getVastaus() + "\"");
    }//GEN-LAST:event_NaytVastausActionPerformed

    /**
     * Avataan uusi tiedosto ja siten uusi ilmentymä tästä sovelluksesta
     *
     * @param evt tapahtuma
     */
    private void AvaaUusiFiluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AvaaUusiFiluActionPerformed

        new BasicGUI().setVisible(true);
        //eli sulkee tän ikkunan, avaa uuden tiedostokyselyn ja avaa guin uudestaan

    }//GEN-LAST:event_AvaaUusiFiluActionPerformed

    /**
     * Suljetaan tämä auki oleva ikkuna, jossa tätä klikataan.
     *
     * @param evt tapahtuma joka tapahtui
     */
    private void SuljeTaaIkkunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuljeTaaIkkunaActionPerformed

        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_SuljeTaaIkkunaActionPerformed

    private void KysSeuraavaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KysSeuraavaKeyTyped
        // TODO add your handling code here:
//        System.out.println(evt);
    }//GEN-LAST:event_KysSeuraavaKeyTyped

    private void formKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyTyped
    }//GEN-LAST:event_formKeyTyped
//
////    /**
////     * @param args the command line arguments
////     */
////    public static void main(String args[]) {
////        /*
////         * Set the Nimbus look and feel
////         */
////        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /*
//     C     //</editor-fold>
//
////        /*
////         * Create and display the form
////         */
////        java.awt.EventQueue.invokeLater(new Runnable() {
////
////            public void run() {
////                new BasicGUI().setVisible(true);
////
////            }
////        });
////    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenuitem2;
    private javax.swing.JMenuItem AvaaUusiFilu;
    private javax.swing.JMenuItem CopyrightInfo;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JLabel KerrottuTeksti;
    private javax.swing.JButton KysEdellinen;
    private javax.swing.JButton KysSeuraava;
    private javax.swing.JTextArea Kysymys;
    private javax.swing.JButton Logiikka;
    private javax.swing.JMenuItem LopetaMenuItem;
    private javax.swing.JMenuBar MenuValikko;
    private javax.swing.JLabel MitenMeni;
    private javax.swing.JButton NaytVastaus;
    private javax.swing.JLabel Onnistuneet;
    private javax.swing.JButton Random;
    private javax.swing.JRadioButton Sanaan;
    private javax.swing.JMenuItem SuljeTaaIkkuna;
    private javax.swing.ButtonGroup SuunnanValitsin;
    private javax.swing.JButton TarkVastaus;
    private javax.swing.JLabel Vaarin;
    private javax.swing.JTextField Vastaus;
    private javax.swing.JRadioButton Vastineeseen;
    private javax.swing.JLabel Yhteensa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
