package UI.GUI;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import sun.nio.cs.ext.GB18030;

/**
 *
 * @author jarmo
 */
public class BasicGUI extends javax.swing.JFrame {

    private boolean kysSuunta = true;
    GuiValiKommunikaatio k = new GuiValiKommunikaatio();

    /**
     * Creates new form BasicGUI
     */
    public BasicGUI() {
        initComponents();


    }

    private void tyhjennaOnnistuminen() {
        MitenMeni.setText("");
    }

    private void disableTarkista() {
        TarkVastaus.setEnabled(false);
    }

    private void enableTarkista() {
        TarkVastaus.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SuunnanValitsin = new javax.swing.ButtonGroup();
        Vastineeseen = new javax.swing.JRadioButton();
        Sanaan = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Kysymys = new javax.swing.JTextArea();
        Vastaus = new javax.swing.JTextField();
        KysSeuraava = new javax.swing.JButton();
        KysEdellinen = new javax.swing.JButton();
        Random = new javax.swing.JButton();
        Logiikka = new javax.swing.JButton();
        TarkVastaus = new javax.swing.JButton();
        Onnistuneet = new javax.swing.JLabel();
        Vaarin = new javax.swing.JLabel();
        Yhteensa = new javax.swing.JLabel();
        KerrottuTeksti = new javax.swing.JLabel();
        MitenMeni = new javax.swing.JLabel();
        NaytVastaus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        MenuValikko = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        LopetaMenuItem = new javax.swing.JMenuItem();
        HelpMenu = new javax.swing.JMenu();
        AboutMenuitem2 = new javax.swing.JMenuItem();
        CopyrightInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kyselyohjelma");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(600, 400));

        SuunnanValitsin.add(Vastineeseen);
        Vastineeseen.setSelected(true);
        Vastineeseen.setText("Sana -> Vastine");
        Vastineeseen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VastineeseenActionPerformed(evt);
            }
        });

        SuunnanValitsin.add(Sanaan);
        Sanaan.setText("Vastine -> Sana");
        Sanaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SanaanActionPerformed(evt);
            }
        });

        Kysymys.setColumns(20);
        Kysymys.setEditable(false);
        Kysymys.setLineWrap(true);
        Kysymys.setRows(5);
        jScrollPane1.setViewportView(Kysymys);

        Vastaus.setToolTipText("Kirjoita vastaus tähän kenttään");

        KysSeuraava.setText("Kysy Seuraava");
        KysSeuraava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KysSeuraavaActionPerformed(evt);
            }
        });

        KysEdellinen.setText("Kysy Edellinen");
        KysEdellinen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KysEdellinenActionPerformed(evt);
            }
        });

        Random.setText("Kysy Satunnainen");
        Random.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RandomActionPerformed(evt);
            }
        });

        Logiikka.setText("Kysy Painotetusti");
        Logiikka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogiikkaActionPerformed(evt);
            }
        });

        TarkVastaus.setText("Tarkista");
        TarkVastaus.setEnabled(false);
        TarkVastaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TarkVastausActionPerformed(evt);
            }
        });

        Onnistuneet.setText("Oikein: 0");

        Vaarin.setText("Vaarin: 0");

        Yhteensa.setText("Yhteensä: 0");

        KerrottuTeksti.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        KerrottuTeksti.setText("Arvaa sanan vastine");

        MitenMeni.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N

        NaytVastaus.setText("NäytäVastaus");
        NaytVastaus.setEnabled(false);
        NaytVastaus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NaytVastausActionPerformed(evt);
            }
        });

        jLabel1.setText("Valitse suunta");

        FileMenu.setText("File");

        LopetaMenuItem.setText("Quit");
        LopetaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LopetaMenuItemActionPerformed(evt);
            }
        });
        FileMenu.add(LopetaMenuItem);

        MenuValikko.add(FileMenu);

        HelpMenu.setText("Help");

        AboutMenuitem2.setText("About");
        AboutMenuitem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AboutMenuitem2ActionPerformed(evt);
            }
        });
        HelpMenu.add(AboutMenuitem2);

        CopyrightInfo.setText("COPYRIGHT");
        CopyrightInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CopyrightInfoActionPerformed(evt);
            }
        });
        HelpMenu.add(CopyrightInfo);

        MenuValikko.add(HelpMenu);

        setJMenuBar(MenuValikko);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Vastaus, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TarkVastaus)))
                        .addGap(104, 104, 104)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Onnistuneet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Vaarin, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Yhteensa, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KerrottuTeksti)
                            .addComponent(jLabel1)
                            .addComponent(Vastineeseen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MitenMeni, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NaytVastaus, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sanaan, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(KysSeuraava, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(KysEdellinen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Random)
                                .addGap(12, 12, 12)
                                .addComponent(Logiikka, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(MitenMeni, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(KerrottuTeksti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NaytVastaus, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Vastineeseen))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sanaan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Onnistuneet)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Vaarin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Yhteensa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Vastaus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TarkVastaus))))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KysSeuraava)
                    .addComponent(KysEdellinen)
                    .addComponent(Random)
                    .addComponent(Logiikka))
                .addGap(118, 118, 118))
        );

        getAccessibleContext().setAccessibleName("Kehys1");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VastineeseenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VastineeseenActionPerformed
        kysSuunta = true;
    }//GEN-LAST:event_VastineeseenActionPerformed

    private void SanaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SanaanActionPerformed
        kysSuunta = false;
    }//GEN-LAST:event_SanaanActionPerformed

    private void KysSeuraavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KysSeuraavaActionPerformed
        //Eli tähän se, mitä seuraavan sanan kysymiseen vaaditaan
//       kysyttavaSana
        String kysyttavaSana = k.kysyNext(kysSuunta);
        Kysymys.setText("Anna sanan: " + kysyttavaSana + " vastine:");
        Vastaus.setText("");
        tyhjennaOnnistuminen();
        enableTarkista();
        NaytVastaus.setEnabled(false);
    }//GEN-LAST:event_KysSeuraavaActionPerformed

    private void KysEdellinenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KysEdellinenActionPerformed
        String kysyttavaSana = k.kysyEdellinen(kysSuunta);
        Kysymys.setText("Anna sanan: " + kysyttavaSana + " vastine:");
        Vastaus.setText("");
        tyhjennaOnnistuminen();
        enableTarkista();
        NaytVastaus.setEnabled(false);
    }//GEN-LAST:event_KysEdellinenActionPerformed

    private void RandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RandomActionPerformed
        // TODO add your handling code here:
        String kysyttava = k.kysyRandom(kysSuunta);
        Kysymys.setText("Anna sanan: " + kysyttava + " vastine:");
        Vastaus.setText("");
        tyhjennaOnnistuminen();
        enableTarkista();
        NaytVastaus.setEnabled(false);
        //tämä kutsuu sitä kuuluisaa Randomia
    }//GEN-LAST:event_RandomActionPerformed

    private void LogiikkaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogiikkaActionPerformed
        // TODO add your handling code here:
        String kysyttava = k.kysyLooginen(kysSuunta);
        Kysymys.setText("Anna sanan: " + kysyttava + " vastine:");
        Vastaus.setText("");
        enableTarkista();
        tyhjennaOnnistuminen();
        NaytVastaus.setEnabled(false);
        //tänne loogisen kyselyn vaatimat kyselyt
    }//GEN-LAST:event_LogiikkaActionPerformed

    private void TarkVastausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TarkVastausActionPerformed
        // TODO add your handling code here:
        tyhjennaOnnistuminen();
        String vastaus = Vastaus.getText();
        boolean onnistui = k.tarkSana(vastaus);
        Onnistuneet.setText("Oikein: " + k.getOikein());
        Vaarin.setText("Väärin: " + k.getVaarin());
        Yhteensa.setText("Yhteensä: " + k.getYhteensa());
        disableTarkista();
        NaytVastaus.setEnabled(true);
        if (onnistui) {
            MitenMeni.setText("Oikein");
            MitenMeni.setForeground(Color.GREEN);
        }
        if (!onnistui) {
            MitenMeni.setText("Väärin");
            MitenMeni.setForeground(Color.RED);
        }
    }//GEN-LAST:event_TarkVastausActionPerformed

    private void LopetaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LopetaMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_LopetaMenuItemActionPerformed

    private void AboutMenuitem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AboutMenuitem2ActionPerformed
        new AboutVersion().setVisible(true);
    }//GEN-LAST:event_AboutMenuitem2ActionPerformed

    private void CopyrightInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CopyrightInfoActionPerformed
        // TODO add your handling code here:

        new Copyright().setVisible(true);
    }//GEN-LAST:event_CopyrightInfoActionPerformed

    private void NaytVastausActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NaytVastausActionPerformed
        JOptionPane.showMessageDialog(null, "Sanan: \"" + k.getKysytty() + "\" vastine on : \""+ k.getVastaus()+ "\"");
    }//GEN-LAST:event_NaytVastausActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BasicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BasicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BasicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BasicGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
//        uk = new UiKommunikaatio(, null)
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new BasicGUI().setVisible(true);

            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AboutMenuitem2;
    private javax.swing.JMenuItem CopyrightInfo;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu HelpMenu;
    private javax.swing.JLabel KerrottuTeksti;
    private javax.swing.JButton KysEdellinen;
    private javax.swing.JButton KysSeuraava;
    private javax.swing.JTextArea Kysymys;
    private javax.swing.JButton Logiikka;
    private javax.swing.JMenuItem LopetaMenuItem;
    private javax.swing.JMenuBar MenuValikko;
    private javax.swing.JLabel MitenMeni;
    private javax.swing.JButton NaytVastaus;
    private javax.swing.JLabel Onnistuneet;
    private javax.swing.JButton Random;
    private javax.swing.JRadioButton Sanaan;
    private javax.swing.ButtonGroup SuunnanValitsin;
    private javax.swing.JButton TarkVastaus;
    private javax.swing.JLabel Vaarin;
    private javax.swing.JTextField Vastaus;
    private javax.swing.JRadioButton Vastineeseen;
    private javax.swing.JLabel Yhteensa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
